sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

before_install:
  - pip install codecov

install: 
  - "pip install -r requirements.txt"
  - "python setup.py install"
  - "python setup.py test"

after_success:
  - codecov